export const environment = {
  production: true,
  firebase: {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  },
  collections: {
    comunas: 'Comunas',
    referidos: 'Referidos',
    iglesias: 'Iglesias',
    roles: 'Roles',
    lideres: 'Lideres',
    barrios: 'Barrios',
    perfil: 'Perfiles',
    vehiculos: 'Vehiculos',
    casasApoyo: 'Casas',
    coordinadorTestigos: 'CoordinadorTestigos',
    testigosAsociados: 'TestigosAsociados',
    puestosVotacion: 'PuestosVotacion',
    cuentavotos: 'Cuentavotos',
    carreras: 'Carreras',
  },
  alerts: { timeOut: 3000, preventDuplicates: true },
};
