export const environment = {
  production: false,
  firebase: {
    apiKey: 'AIzaSyClvFEPxZZf_q28kiipbROeHzsPbAAdlhk',
    authDomain: 'lida-dev-f9291.firebaseapp.com',
    projectId: 'lida-dev-f9291',
    storageBucket: 'lida-dev-f9291.firebasestorage.app',
    messagingSenderId: '78286679625',
    appId: '1:78286679625:web:5621c2157c26df010f1998',
    measurementId: 'G-JXG93QVL1M',
  },
  collections: {
    comunas: 'Comunas',
    referidos: 'Referidos',
    iglesias: 'Iglesias',
    roles: 'Roles',
    lideres: 'Lideres',
    barrios: 'Barrios',
    perfil: 'Perfiles',
    vehiculos: 'Vehiculos',
    casasApoyo: 'Casas',
    testigos: 'Testigos',
    puestosVotacion: 'PuestosVotacion',
    cuentavotos: 'Cuentavotos',
    carreras: 'Carreras',
  },
  alerts: { timeOut: 3000, preventDuplicates: true },
};
