export const environment = {
  production: false,
  firebase: {
    apiKey: process.env['FIREBASE_API_KEY_PROD'],
    authDomain: process.env['FIREBASE_AUTH_DOMAIN_PROD'],
    projectId: process.env['FIREBASE_PROJECT_ID_PROD'],
    storageBucket: process.env['FIREBASE_STORAGE_BUCKET_PROD'],
    messagingSenderId: process.env['FIREBASE_MESSAGING_SENDER_ID_PROD'],
    appId: process.env['FIREBASE_APP_ID_PROD'],
    measurementId: process.env['FIREBASE_MEASUREMENT_ID_PROD'],
  },
  collections: {
    comunas: 'Comunas',
    referidos: 'Referidos',
    iglesias: 'Iglesias',
    roles: 'Roles',
    lideres: 'Lideres',
    barrios: 'Barrios',
    perfil: 'Perfiles',
    vehiculos: 'Vehiculos',
    casasApoyo: 'Casas',
    testigos: 'Testigos',
    puestosVotacion: 'PuestosVotacion',
    cuentavotos: 'Cuentavotos',
    carreras: 'Carreras',
  },
  alerts: { timeOut: 3000, preventDuplicates: true },
};
